### PR TITLE
Added new homepage icons

### PR DESCRIPTION
**Pull request by siddig-cmd**
New homepage icons

https://app.clubhouse.io/stateofthedapps/story/3193/replace-homepage-dapp-icons

image

### CODE REVIEW

**Comment by jorisbontje** [comment]
The steemit icon with "social" as label (`assets/images/dapp-icons/0.jpg`) is still there...

**Comment by jorisbontje** [comment]
Just removing the file alone isn't enough, as it is still referenced in `pages/DappsNew.vue`
This also gives a compilation error:

```
 ERROR  Failed to compile with 1 errors                                               friendly-errors 13:17:34

This dependency was not found:                                                        friendly-errors 13:17:34
                                                                                      friendly-errors 13:17:34
* assets/images/dapp-icons/0.jpg in ./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/DappsNew.vue?vue&type=template&id=3848bd83&scoped=true&
```

**Comment by SiddigZeidan** [comment]
Should all be working and correct now:
image

**Comment by siddig-cmd** [comment]
Should all be working and correct now:
image

**Comment by jorisbontje** [comment]
Looking good!

**Pull request merged**
