### PR TITLE
Don't accept *.slack.com for Slack urls

### PR DESCRIPTION
**Pull request by robyedlin**

### CODE REVIEW

**Comment by robyedlin** [comment]
@jorisbontje Where did you find the SotD slack invite url? Looks like you made a CNAME on another url.

**Comment by jorisbontje** [comment]
Typically this is a third party application that you install, like:
* https://github.com/rauchg/slackin
* https://github.com/outsideris/slack-invite-automation

Alternatively you can create an invite url from within the slack admin interface, but this typically expires after a couple uses and is generally a pain to keep up to date.

**Comment by robyedlin** [comment]
Ok, so how can we make this input work? Do we need to link to one of these third-party apps?

**Comment by robyedlin** [comment]
Seems too confusing to include as a field, maybe.

**Comment by jorisbontje** [comment]
Fine for now. we can iterate on this to improve

**Pull request merged**
